services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    depends_on:
    - redis
    ports:
      - '81:5000'
    environment:
      - PORT=5000
      - REDIS_HOSTS=redis://redis:6379
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    depends_on:
    - redis
    ports:
      - '82:5000'
    environment:
      - PORT=5000
      - REDIS_HOSTS=redis://redis:6379
  nginx:
    build: ./nginx
    ports:
    - '7000:80'
    depends_on:
    - web1
    - web2

