services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  bg1:
    restart: on-failure
    image: bgjob10
    hostname: bg1
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '81:3000'
  bg2:
    restart: on-failure
    image: bgjob10
    hostname: bg2
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '82:3000'
  bg3:
    restart: on-failure
    image: bgjob10
    hostname: bg3
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '83:3000'
  bg4:
    restart: on-failure
    image: bgjob10
    hostname: bg4
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '84:3000'
  bg5:
    restart: on-failure
    image: bgjob10
    hostname: bg5
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '85:3000'
  bg6:
    restart: on-failure
    image: bgjob10
    hostname: bg6
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '86:3000'
  bg7:
    restart: on-failure
    image: bgjob10
    hostname: bg7
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '87:3000'
  bg8:
    restart: on-failure
    image: bgjob10
    hostname: bg8
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '88:3000'
  bg9:
    restart: on-failure
    image: bgjob10
    hostname: bg9
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '89:3000'
  bg10:
    restart: on-failure
    image: bgjob10
    hostname: bg10
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ: amqp://guest:guest@rabbitmq:5672
    ports:
      - '90:3000'
  nginx:
    build: ./nginx
    ports:
    - '7000:80'
    depends_on:
    - bg1
    - bg2
    - bg3
    - bg4
    - bg5
    - bg6
    - bg7
    - bg8
    - bg9
    - bg10

